### ISSUE TITLE
epic: track software packages and configurations

### ISSUE THREAD

**Issue by jamesericdavidson** [jamesericdavidson/jimbOS-bluefin-dx#17]
- [ ] system-level [dotfiles](https://codeberg.org/jamesericdavidson/new-dotfiles)
  [`profile`](https://github.com/jamesericdavidson/jimbOS-bluefin-dx/blob/main/jimbOS_profile.sh) is already included.
- [ ] brew packages (`Brewfile`/`bluefin-cli`)
- [ ] flatpak (system) packages (uBlue first-time setup)
  - [ ] (system) [overrides](https://codeberg.org/jamesericdavidson/flatpak-overrides)
    Not sure about the best way of tracking/updating these.
- [ ] GNOME modifications
  Like [Bluefin makes Ubuntu-esque changes](https://github.com/ublue-os/bluefin/issues/1743#issue-2567606319), make jimbOS use Tweaks (such as Papirus icons; is `adw-gtk3` already enabled in Bluefin?)
